/cancel powerup
UNICT-DMI/Telegram-SpottedDMI-Bot pull request #19
Opened 2021-01-22 18:45 UTC by TendTo

- The /cancel command now also allows the user to remove a post that is still pending, allowing him to spot immediately.
- The user tags used to show who, among the admins, approved or rejected a pending post, can be turned in inoffensive text (removing the @ at the beginning).
- Fixed a pesky bug that made the bot unresponsive to further /spots and forced the user to use the /cancel command.
- Some very minor refactoring.

2021-01-22 19:12 UTC, Helias requested changes

2021-01-22 19:12 UTC, Helias commented on modules/utils/__init__.py
> +REACTION = {'0': "👎", '1': "👍", '2': "🤣", '3': "😡", '4': "🥰"}
change '0', '1', with 'thumbsdown', 'thumbsup' etc.

2021-01-22 19:12 UTC, Helias commented on modules/data/meme_data.py
> +            return None, None
:heart:

2021-01-23 13:31 UTC, drendog approved these changes

2021-01-23 13:32 UTC, drendog reviewed
****

2021-01-29 12:57 UTC, merged

2021-01-29 14:25 UTC, Helias commented
😢