fix: added check in the forwarding handler to avoid non-spot messages
UNICT-DMI/Telegram-SpottedDMI-Bot pull request #35
Opened 2021-03-13 11:58 UTC by TendTo

- fix: added check in the forwarding handler to avoid non-spot messages 
  - This should solve the key error we were receiving
- feat: DbManager - added multiple rows support 
  - Added support for bulk addition of rows, even though this feature is now unused
- refactor: moved get_user_sign from EventInfo -> User 
  - Just a more appropriate location

2021-03-13 12:17 UTC, Helias requested changes

2021-03-13 12:17 UTC, Helias commented on modules/data/db_manager.py
> +                logger.error("DbManager.count_from: %s", e)
a bit redundant code here, you could create a function for this try except and make only try_err("different string") or similar

2021-03-13 15:44 UTC, Helias approved these changes

2021-03-14 23:52 UTC, drendog approved these changes

2021-03-15 10:55 UTC, merged